name: Coletar Mercado Livre -> Supabase

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar .env do job com seus secrets
        run: |
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}" >> .env
          echo "MELI_CLIENT_ID=${{ secrets.MELI_CLIENT_ID }}" >> .env
          echo "MELI_CLIENT_SECRET=${{ secrets.MELI_CLIENT_SECRET }}" >> .env
          echo "MELI_ACCESS_TOKEN=${{ secrets.MELI_ACCESS_TOKEN }}" >> .env
          echo "MELI_REFRESH_TOKEN=${{ secrets.MELI_REFRESH_TOKEN }}" >> .env
          echo "QUERIES_MELI=${{ secrets.QUERIES_MELI }}" >> .env

      - name: Rodar coletor
        run: python collectors/run_fetch.py
