name: Coletar Mercado Livre -> Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # opcional: a cada 3h

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (robusto)
        run: |
          python -m pip install --upgrade pip
          if [ -f infra/requirements.txt ]; then
            echo ">> usando infra/requirements.txt"
            pip install -r infra/requirements.txt
          elif [ -f requirements.txt ]; then
            echo ">> usando requirements.txt (raiz)"
            pip install -r requirements.txt
          else
            echo "NÃO ENCONTREI requirements.txt"; exit 1
          fi

      - name: Criar .env com secrets
        run: |
          cat > .env << 'EOF'
          SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}
          MELI_CLIENT_ID=${{ secrets.MELI_CLIENT_ID }}
          MELI_CLIENT_SECRET=${{ secrets.MELI_CLIENT_SECRET }}
          MELI_ACCESS_TOKEN=${{ secrets.MELI_ACCESS_TOKEN }}
          MELI_REFRESH_TOKEN=${{ secrets.MELI_REFRESH_TOKEN }}
          QUERIES_MELI=${{ secrets.QUERIES_MELI }}
          EOF
          echo "OK .env"

      - name: Rodar coletor
        working-directory: collectors
        run: python run_fetch.py
